metadata:
  projectname: susi_android
  author: FOSSASIA
  version: development
  autoindex:
    apidoc:
      javadoc:
        show: true

build:
  source: docs
  theme:
    name: sphinx_fossasia_theme

publish:
  ghpages:
    url: play.google.com/apps/testing/ai.susi
